# -*- coding: utf-8 -*-
"""Image_to_Pencil_Sketch_with_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14j3ANj3aONj6OmHQVRqPMKIZBIMHBePG

# LetsGrowMore (LGMVIP) - May 2022

Sanjay A V - Data Science Intern

## BEGINNER LEVEL TASK

## Task 4 -  Image to Pencil Sketch with Python
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

BGR_image = cv2.imread('lion.jpg')

plt.imshow(BGR_image)
plt.title("BGR_Image",fontstyle='italic', fontsize=10,color="gray")
plt.axis(False)
plt.show()

RGB_image = cv2.cvtColor(BGR_image, cv2.COLOR_BGR2RGB)
plt.imshow(RGB_image)
plt.title("RGB_Image",fontstyle='italic', fontsize=10,color="gray")
plt.axis(False)
plt.show()

GreyScale_image = cv2.cvtColor(RGB_image, cv2.COLOR_RGB2GRAY)
plt.imshow(GreyScale_image)
plt.title("Grey_Scale_Image",fontstyle='italic', fontsize=10,color="gray")
plt.axis(False)
plt.show()

Inverted_image = cv2.bitwise_not(GreyScale_image)
plt.imshow(Inverted_image)
plt.title("Inverted_GS_Image",fontstyle='italic', fontsize=10,color="gray")
plt.axis(False)
plt.show()

Blurred_image = cv2.GaussianBlur(Inverted_image, (111,111), 0)
plt.imshow(Blurred_image)
plt.title("Blurred_Image",fontstyle='italic', fontsize=10,color="gray")
plt.axis(False)
plt.show()

InvertedBlur_image = cv2.bitwise_not(Blurred_image)
plt.imshow(InvertedBlur_image)
plt.title("Inverted_Blurred_Image",fontstyle='italic', fontsize=10,color="gray")
plt.axis(False)
plt.show()

RGBSketch_image = cv2.divide(GreyScale_image, InvertedBlur_image, scale=256.0)
plt.imshow(RGBSketch_image)
plt.title("RGB_Sketch_Image",fontstyle='italic', fontsize=10,color="gray")
plt.axis(False)
plt.show()

PencilSketch_image = cv2.cvtColor(RGBSketch_image, cv2.COLOR_RGB2BGR)
plt.figure(figsize = (8,8))
plt.title("Pencil_Sketch_Image",fontstyle='italic', fontsize=20,color="gray")
plt.imshow(PencilSketch_image)
plt.axis(False)
plt.show()

cv2.imwrite("lion sketch.jpg", PencilSketch_image)

Comp = np.concatenate((RGB_image, PencilSketch_image), axis=1)
plt.figure(figsize = (8,8))
plt.imshow(Comp)
plt.axis(False)
plt.show()